"""
Definitions of common variables for the VNF Devstack test in robot suites."""

DEVSTACK_IP = "192.168.122.222"
DEVSTACK_USER = "stack"
DEVSTACK_PSWD = "admin123"
SSH_PORT = "22"
PROMPT= ":~$"
SLEEP_TIME = "30"
TIMEOUT = "20"
