"""
Definitions of common variables for the VNF Devstack test in robot suites."""

DEVSTACK_IP = "192.168.203.6"
DEVSTACK_USER = "testpc"
DEVSTACK_PSWD = "test123"
SSH_PORT = "22"
PROMPT= ":~$"
SLEEP_TIME = "30"
TIMEOUT = "20"
